import type { MagArticle, MagTaxonomyTerm } from "../../types";

export const mockMarkets: readonly MagTaxonomyTerm[] = [
  { name: "بورس ایران", slug: "iran-stock" },
  { name: "طلا و دلار", slug: "gold-currency" },
  { name: "کریپتو", slug: "crypto" },
  { name: "فارکس", slug: "forex" },
  { name: "اقتصاد جهانی", slug: "global-economy" },
  { name: "مسکن", slug: "housing" },
];

export const mockArticles: readonly MagArticle[] = [
  {
    id: "1831",
    slug: "aud-usd-upside-risk-analysis",
    title: "دلار استرالیا پس از تثبیت نرخ بهره تقویت شد؛ مقاومت ۰٫۷۰۷۵ مانع رشد پایدار است",
    excerpt: "بررسی عوامل اثرگذار بر مسیر کوتاه‌مدت دلار استرالیا پس از تصمیم بانک مرکزی.",
    publishedAt: "2026-08-17T18:59:26+03:30",
    readingTime: 7,
    whyItMatters: "تصمیم بانک مرکزی استرالیا می‌تواند جهت جفت‌ارز را در هفته پیش رو تغییر دهد.",
    market: { name: "فارکس", slug: "forex" },
    contentType: { name: "اخبار", slug: "news" },
    featuredImage: {
      src: "https://thefinance.ir/mag/wp-content/uploads/2026/08/aud-usd-upside-risk-analysis.jpg",
      alt: "نمودار دلار استرالیا به دلار آمریکا",
      width: 1376,
      height: 768,
    },
  },
  {
    id: "1873",
    slug: "10-reason-why-most-traders-fail",
    title: "چرا اکثر معامله‌گران شکست می‌خورند؟ راه‌های جلوگیری از آن",
    excerpt: "مروری بر خطاهای مدیریت ریسک و تصمیم‌های هیجانی معامله‌گران.",
    publishedAt: "2026-08-17T11:00:53+03:30",
    readingTime: 12,
    whyItMatters: "بخش بزرگی از زیان معامله‌گران از روش تحلیل نیست؛ از نحوه اجرای تصمیم می‌آید.",
    market: { name: "اقتصاد جهانی", slug: "global-economy" },
    contentType: { name: "آموزش", slug: "education" },
    featuredImage: {
      src: "https://thefinance.ir/mag/wp-content/uploads/2026/08/شاخص-1.jpg",
      alt: "چرا اکثر معامله‌گران شکست می‌خورند؟",
      width: 1200,
      height: 800,
    },
  },
  {
    id: "1838",
    slug: "notcoin-explore",
    title: "نات کوین چیست؟ آموزش کسب درآمد از Notcoin",
    excerpt: "از بازی تلگرامی تا توکن NOT و اکوسیستم شبکه TON.",
    publishedAt: "2026-08-16T15:31:00+03:30",
    readingTime: 9,
    whyItMatters: "شناخت مدل اقتصادی پروژه کمک می‌کند تبلیغات آن را از کاربرد واقعی جدا کنیم.",
    market: { name: "کریپتو", slug: "crypto" },
    contentType: { name: "آموزش", slug: "education" },
    featuredImage: {
      src: "https://thefinance.ir/mag/wp-content/uploads/2026/08/نات-کوین.jpg",
      alt: "نات کوین",
      width: 1200,
      height: 800,
    },
  },
  {
    id: "1796",
    slug: "zig-zag-indicator",
    title: "اندیکاتور زیگ زاگ (Zig Zag) چیست؟",
    excerpt: "روشی برای فیلتر کردن نویز و دیدن ساختار اصلی حرکت قیمت.",
    publishedAt: "2026-08-15T13:17:52+03:30",
    readingTime: 8,
    whyItMatters: "زیگ زاگ ابزار پیش‌بینی نیست، اما سوئینگ‌های مهم را خواناتر می‌کند.",
    market: { name: "فارکس", slug: "forex" },
    contentType: { name: "آموزش", slug: "education" },
    featuredImage: {
      src: "https://thefinance.ir/mag/wp-content/uploads/2026/08/شاخص.jpg",
      alt: "اندیکاتور زیگ زاگ",
      width: 1200,
      height: 800,
    },
  },
  {
    id: "1755",
    slug: "fundamental-analysis",
    title: "تحلیل فاندامنتال چیست؟ آموزش کامل تحلیل بنیادی",
    excerpt: "بررسی عوامل پشت ارزش یک دارایی، فراتر از حرکت روزانه قیمت.",
    publishedAt: "2026-08-11T18:23:02+03:30",
    readingTime: 14,
    whyItMatters: null,
    market: { name: "اقتصاد جهانی", slug: "global-economy" },
    contentType: { name: "آموزش", slug: "education" },
    featuredImage: {
      src: "https://thefinance.ir/mag/wp-content/uploads/2026/08/تحلیل-فاندامنتال-چیست.jpg",
      alt: "تحلیل فاندامنتال چیست",
      width: 1200,
      height: 800,
    },
  },
  {
    id: "1729",
    slug: "technical-analysis",
    title: "تحلیل تکنیکال چیست؟ آموزش از صفر تا صد",
    excerpt: "خواندن رفتار قیمت و حجم با استفاده از نمودارها و الگوها.",
    publishedAt: "2026-08-10T15:16:43+03:30",
    readingTime: 16,
    whyItMatters: null,
    market: { name: "اقتصاد جهانی", slug: "global-economy" },
    contentType: { name: "آموزش", slug: "education" },
    featuredImage: {
      src: "https://thefinance.ir/mag/wp-content/uploads/2026/08/شاخص-تحلیل-تکنیکال-چیست.jpg",
      alt: "آموزش تحلیل تکنیکال",
      width: 1200,
      height: 800,
    },
  },
  {
    id: "1699",
    slug: "what-is-airdrop",
    title: "ایردراپ چیست؟ راهنمای دریافت ارز دیجیتال رایگان",
    excerpt: "فرصت‌ها و ریسک‌های پنهان پشت وعده توکن رایگان.",
    publishedAt: "2026-08-06T13:22:59+03:30",
    readingTime: 11,
    whyItMatters: null,
    market: { name: "کریپتو", slug: "crypto" },
    contentType: { name: "آموزش", slug: "education" },
    featuredImage: {
      src: "https://thefinance.ir/mag/wp-content/uploads/2026/08/ایردراپ-چیست.jpg",
      alt: "ایردراپ چیست",
      width: 1200,
      height: 800,
    },
  },
  {
    id: "1647",
    slug: "tradingview-guide",
    title: "آموزش تریدینگ ویو؛ راهنمای ابزارها و تنظیمات",
    excerpt: "چطور یک فضای تحلیل خلوت و قابل استفاده بسازیم.",
    publishedAt: "2026-08-05T12:29:13+03:30",
    readingTime: 13,
    whyItMatters: null,
    market: { name: "فارکس", slug: "forex" },
    contentType: { name: "آموزش", slug: "education" },
    featuredImage: {
      src: "https://thefinance.ir/mag/wp-content/uploads/2026/08/آموزش-تریدینگ-ویو.jpg",
      alt: "آموزش تریدینگ ویو",
      width: 1200,
      height: 800,
    },
  },
  {
    id: "1606",
    slug: "iran-stock-1405",
    title: "بورس ایران در سال ۱۴۰۵؛ رشد بازار یا ادامه رکود؟",
    excerpt: "نرخ بهره، دلار، سیاست‌گذاری و جریان نقدینگی چه مسیری می‌سازند؟",
    publishedAt: "2026-08-02T12:49:01+03:30",
    readingTime: 10,
    whyItMatters: null,
    market: { name: "بورس ایران", slug: "iran-stock" },
    contentType: { name: "تحلیل", slug: "analysis" },
    featuredImage: {
      src: "https://thefinance.ir/mag/wp-content/uploads/2026/08/پیش-بینی-بورس-ایران-در-1405.jpg",
      alt: "بررسی بورس ایران در سال ۱۴۰۵",
      width: 1200,
      height: 800,
    },
  },
  {
    id: "1589",
    slug: "miner-income-1405",
    title: "درآمد دستگاه ماینر چقدر است؟",
    excerpt: "محاسبه درآمد و هزینه استخراج ارزهای دیجیتال در سال ۱۴۰۵.",
    publishedAt: "2026-08-01T11:30:22+03:30",
    readingTime: 9,
    whyItMatters: null,
    market: { name: "کریپتو", slug: "crypto" },
    contentType: { name: "آموزش", slug: "education" },
    featuredImage: {
      src: "https://thefinance.ir/mag/wp-content/uploads/2026/08/درآمد-ماینرها-1.jpg",
      alt: "درآمد ماینرها در ۱۴۰۵",
      width: 1200,
      height: 800,
    },
  },
  {
    id: "1547",
    slug: "capital-during-war",
    title: "نگهداری سرمایه در زمان جنگ",
    excerpt: "در دوره بحران، حفظ نقدشوندگی و قدرت خرید چه معنایی دارد؟",
    publishedAt: "2026-07-29T11:34:21+03:30",
    readingTime: 8,
    whyItMatters: null,
    market: { name: "طلا و دلار", slug: "gold-currency" },
    contentType: { name: "اخبار", slug: "news" },
    featuredImage: {
      src: "https://thefinance.ir/mag/wp-content/uploads/2026/07/سرمایه-گذاری-زمان-جنگ-2.jpg",
      alt: "سرمایه‌گذاری در زمان جنگ",
      width: 1200,
      height: 800,
    },
  },
  {
    id: "1522",
    slug: "gold-fund-or-physical-gold",
    title: "صندوق سرمایه‌گذاری طلا یا طلای فیزیکی؟",
    excerpt: "مقایسه نقدشوندگی، حباب، هزینه و شیوه نگهداری دو انتخاب.",
    publishedAt: "2026-07-28T13:35:09+03:30",
    readingTime: 9,
    whyItMatters: null,
    market: { name: "طلا و دلار", slug: "gold-currency" },
    contentType: { name: "تحلیل", slug: "analysis" },
    featuredImage: {
      src: "https://thefinance.ir/mag/wp-content/uploads/2026/07/سرمایه-گذاری-صندوق-طلا-1.jpg",
      alt: "مقایسه صندوق طلا و طلای فیزیکی",
      width: 1200,
      height: 800,
    },
  },
];
